/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainView', {
    extend: 'Ext.container.Viewport',
	id:'MainView',
	itemId:'MainView',
    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.form.Label',
        'Ext.button.Cycle',
        'Ext.menu.Menu',
        'Ext.menu.CheckItem'
    ],
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'north',
                    height: 100,
                    itemId: 'headerPanel',
                    header: false,
                    title: 'Header',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'ADMIN',
									id:'returnHome',
									itemId:'returnHome',
                                },
                                {
                                    xtype: 'cycle',
                                    text: 'Customer',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'Password',
												id:'customer',
												itemId:'customer',
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'cycle',
                                    text: 'Business',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'Register',
												id :'register',
												itemId:'register',
                                            },
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'Store',
												id:'store',
												itemId:'store',
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'cycle',
                                    text: 'System',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'Setting',
												id : 'system',
												itemId:'system',
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'label',
                                    text: 'Welcome：'
                                },
                                {
                                    xtype: 'label',
                                    text: 'admin',
									id:'welcome',
									itemId:'welcome',								
								
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Home'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    itemId: 'contentPanel',
                    bodyPadding: 10,
                    title: 'Unread Message from JMS:',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Welcome to the admin system :'
                                },
                                {
                                    xtype: 'label',
                                    text: '0',
									id:'unreadMessage',
									itemId:'unreadMessage',
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});