/*
 * File: app/view/MainViewport.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.storeView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainviewport',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.form.Label',
        'Ext.button.Cycle',
        'Ext.menu.Menu',
        'Ext.menu.CheckItem',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.grid.View'
    ],

    layout: 'fit',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    header: false,
                    manageHeight: false,
                    title: 'Countdown',
                    layout: {
                        type: 'hbox',
                        pack: 'center',
                        padding: 10
                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            flex: 1,
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'ADMIN',
                                    id : 'returnHome',
            						itemId : 'returnHome',
                                },
                                {
                                    xtype: 'cycle',
                                    text: 'Customer',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'Password',
                                                id : 'customer',
                								itemId : 'customer',
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'cycle',
                                    text: 'Business',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'Register',
                                                id : 'register',
                								itemId : 'register',
                                            },
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'Store',
                                                id : 'store',
                								itemId : 'store',
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'cycle',
                                    text: 'System',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'Setting',
                                                id : 'system',
                								itemId : 'system',
                                            }
                                        ]
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            flex: 1,
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Home /'
                                },
                                {
                                    xtype: 'label',
                                    text: 'Business /'
                                },
                                {
                                    xtype: 'label',
                                    text: 'Store'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            dock: 'top',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    html: {
                                        
                                    },
                                    width: 700,
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'middle',
                                                pack: 'center'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    autoScroll: true,
                                    title: 'Business Store:',
                                    store : Ext.create('MyApp.store.MyStore'),
                                    id : 'searchResultGrid',
                					itemId : 'searchResultGrid',
                                    columns: [ {
                						xtype : 'gridcolumn',
                						dataIndex : 'businessId',
                						text : 'Id'
                						},
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'realName',
                                            text: 'Name'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'idCardId',
                                            text: 'ID Card'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'licenseId',
                                            text: 'License'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'statusName',
                                            text: 'Status'
                                        }
                                    ],
                                    selModel : Ext.create('Ext.selection.CheckboxModel', {
                						mode : 'SINGLE'
                					}),
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    text: '设为热门',
                                                    id : 'update',
                        							itemId : 'update',
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: '停止营业',
                                                    id : 'delete',
                        							itemId : 'delete',
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: '取消停止',
                                                    id : 'cancle',
                        							itemId : 'cancle',
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});