/*
 * File: app/controller/Countdown.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.storeController', {
    extend: 'Ext.app.Controller',

    init: function(application) {
        this.control({
            '#returnHome':{
 			   click:this.returnHome
 		   },
 			'#customer':{
 				click:this.customer
 			},
 			'#register':{
 				click:this.register
 			},
 			'#store':{
 				click:this.store
 			},
 			'#system':{
 				click:this.system
 			},
 			'#update':{
 				click:this.update
 			},
 			'#delete':{
 				click:this.stop
 			},
 			'#cancle':{
 				click:this.cancle
 			}
 			 			
         
        });
    },returnHome:function(){
		window.location.href='/home/index.html';
	},
	customer:function(){
		window.location.href='/customer/customer.html';
	},
	register:function(){
		window.location.href='/business/business.html';
	},
	store:function(){
		window.location.href='/store/store.html';
	},
	system:function(){
		window.location.href='/setting/setting.html';
	},
	update:function(){
		var searchResultGrid = Ext.getCmp('searchResultGrid');
		var selectedRows = searchResultGrid.getSelectionModel().getSelection();
		if(selectedRows.length!=0){
			var model=selectedRows[0].data;
			var businessId=model.businessId;
			Ext.Ajax.request({
				url:'/updateStatusToBeHot',
				params:{
					businessId:businessId
				},
				success:function(response){
					var jsonObj = response.responseText;
					var status=JSON.parse(jsonObj);
					if(("success")==(status.status)){
						Ext.MessageBox.alert("tip","Success");
						Ext.getStore("MyStore").reload();

					}else{
						Ext.MessageBox.alert("tip","Failure");
					}
				}
			});
		}
	},
	stop:function(){
		var searchResultGrid = Ext.getCmp('searchResultGrid');
		var selectedRows = searchResultGrid.getSelectionModel().getSelection();
		if(selectedRows.length!=0){
			var model=selectedRows[0].data;
			var businessId=model.businessId;
			Ext.Ajax.request({
				url:'/updateStatusToBeStop',
				params:{
					businessId:businessId
				},
				success:function(response){
					var jsonObj = response.responseText;
					var status=JSON.parse(jsonObj);
					if(("success")==(status.status)){
						Ext.MessageBox.alert("tip","Success");
						Ext.getStore("MyStore").reload();

					}else{
						Ext.MessageBox.alert("tip","Failure");
					}
				}
			});
		}
	},
	cancle:function(){
		var searchResultGrid = Ext.getCmp('searchResultGrid');
		var selectedRows = searchResultGrid.getSelectionModel().getSelection();
		if(selectedRows.length!=0){
			var model=selectedRows[0].data;
			var businessId=model.businessId;
			Ext.Ajax.request({
				url:'/updateStatusToBeNormal',
				params:{
					businessId:businessId
				},
				success:function(response){
					var jsonObj = response.responseText;
					var status=JSON.parse(jsonObj);
					if(("success")==(status.status)){
						Ext.MessageBox.alert("tip","Success");
						Ext.getStore("MyStore").reload();

					}else{
						Ext.MessageBox.alert("tip","Failure");
					}
				}
			});
		}
	}

});
