/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.settingView', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.form.Label',
        'Ext.button.Cycle',
        'Ext.menu.Menu',
        'Ext.menu.CheckItem',
        'Ext.form.field.Text',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View'
    ],

    itemId: 'settingView',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'north',
                    height: 100,
                    itemId: 'headerPanel',
                    header: false,
                    title: 'Header',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'ADMIN',
									id:'returnHome',
									itemId:'returnHome',
                                },
                                {
                                    xtype: 'cycle',
                                    text: 'Customer',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'Password',
												id:'customer',
												itemId:'customer',
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'cycle',
                                    text: 'Business',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'Register',
												id :'register',
												itemId:'register',
                                            },
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'Store',
												id:'store',
												itemId:'store',
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'cycle',
                                    text: 'System',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menucheckitem',
                                                text: 'Setting',
												id : 'system',
												itemId:'system',
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'label',
                                    text: 'Welcome'
                                },
                                {
                                    xtype: 'label',
                                    text: 'admin',
									id:'welcome',
									itemId:'welcome',								
								
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Home /'
                                },
                                {
                                    xtype: 'label',
                                    text: 'System /'
                                },
                                {
                                    xtype: 'label',
                                    text: 'Setting'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    itemId: 'contentPanel',
                    bodyPadding: 10,
                    header: false,
                    title: 'Content',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            title: '订单期限',
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: '自动过期时限',
											value:'3',
											id:'celTime',
											itemId:'celTime',
                                        },
                                        {
                                            xtype: 'button',
                                            text: '修改',
											id:'auto-cel',
											itemId:'auto-cel',
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: '自动完成期限',
											value:'5',
											id:'acpTime',
											itemId:'acpTime',
                                        },
                                        {
                                            xtype: 'button',
                                            text: '修改',
											id:'auto-acp',
											itemId:'auto-acp',
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            height: 223,
                            title: '客服电话',
                            items: [
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Tel',
									value:'4008008200',
									id:'newTel',
									itemId:'newTel',
							
                                },
                                {
                                    xtype: 'button',
                                    text: '修改',
									id:'updateTel',
									itemId:'updateTel',
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            title: '餐厅种类',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: '种类'
                                }
                            ],
                            viewConfig: {
                                emptyText: '',
                                enableTextSelection: false
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: '删除'
                                        },
                                        {
                                            xtype: 'button',
                                            text: '添加'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});