--插入 伪静态表的DATA 以后需要做数据迁移的时候,作为初始化数据准备


--角色类型:Role
INSERT INTO ROLE(ROLE_ID, ROLE_NAME) VALUES (1,'Administrator');
INSERT INTO ROLE(ROLE_ID, ROLE_NAME) VALUES (2,'Business');
INSERT INTO ROLE(ROLE_ID, ROLE_NAME) VALUES (3,'Customer');

--状态表:Status
INSERT INTO STATUS(STATUS_ID, STATUS_NAME) VALUES (1,'APPROVING');                --审核中
INSERT INTO STATUS(STATUS_ID, STATUS_NAME) VALUES (2,'DELETED');                  --删除
INSERT INTO STATUS(STATUS_ID, STATUS_NAME) VALUES (3,'REJECTED');                 --被拒绝成为商家
INSERT INTO STATUS(STATUS_ID, STATUS_NAME) VALUES (4,'ACCEPTED');                 --接受成为商家
INSERT INTO STATUS(STATUS_ID, STATUS_NAME) VALUES (5,'HOT');                      --热门的~被审核通过的商家~


INSERT INTO STATUS(STATUS_ID, STATUS_NAME) VALUES (10,'NEW_ORDER');               --新订单
INSERT INTO STATUS(STATUS_ID, STATUS_NAME) VALUES (11,'BUSINESS_ACCEPTED');       --已接收
INSERT INTO STATUS(STATUS_ID, STATUS_NAME) VALUES (12,'FOOD_SEND_OUT');           --送货中
INSERT INTO STATUS(STATUS_ID, STATUS_NAME) VALUES (13,'FINISHED');                --已完成
--商家工作状态表:WorkStatus






INSERT INTO BUSINESS_TAG(BUSINESS_TAG_ID, BUSINESS_ID, BUSINESS_TAG_NAME) VALUES (SEQ_BUSINESS_TAG.nextval,41,'中餐');

INSERT INTO BUSINESS_TAG(BUSINESS_TAG_ID, BUSINESS_ID, BUSINESS_TAG_NAME) VALUES (SEQ_BUSINESS_TAG.nextval,41,'西餐');
INSERT INTO BUSINESS_TAG(BUSINESS_TAG_ID, BUSINESS_ID, BUSINESS_TAG_NAME) VALUES (SEQ_BUSINESS_TAG.nextval,41,'饮料');