/*
 * File: app/controller/CarForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CascadingSelect.controller.LoginController', {
    extend: 'Ext.app.Controller',


    init: function(application) {
        this.control({
            '#loginButton':{
				click:this.login
			}
        });
    },
	
	login:function(){
		var loginName=Ext.getCmp('loginName').getValue();
		var loginPassword=Ext.getCmp('loginPassword').getValue();
		Ext.Ajax.request({
			url: '/adminlogin',
			params: {
				name: loginName,
				encryptedPassword:loginPassword
			},
			success: function(response){
				var jsonObj = response.responseText;
				var status=JSON.parse(jsonObj);
				if(("success")==(status.status)){
					window.location.href='/home/index.html';
				}else{
					Ext.MessageBox.alert('Tip','Please input the right username and password');
					Ext.getCmp('loginName').setValue("");
					Ext.getCmp('loginPassword').setValue("");
				}
			}
		});
	}
});
