/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.settingController', {
    extend: 'Ext.app.Controller',

    init: function(application) {
        this.control({
            '#returnHome':{
			   click:this.returnHome
		   },
			'#customer':{
				click:this.customer
			},
			'#register':{
				click:this.register
			},
			'#store':{
				click:this.store
			},
			'#system':{
				click:this.system
			},
			'#auto-cel':{
				click:this.autoCel
			},
			'#auto-acp':{
				click:this.autoAcp
			},
			'#updateTel':{
				click:this.updateTel
			}
        });
    },
	returnHome:function(){
		window.location.href='/home/index.html';
	},
	customer:function(){
		window.location.href='/customer/customer.html';
		},
	register:function(){
		window.location.href='/business/business.html';
	},
	store:function(){
		window.location.href='/store/store.html';
	},
	system:function(){
		window.location.href='/setting/setting.html';
	},
	autoCel:function(){
		var celTime=Ext.getCmp('celTime').getValue();
		Ext.Ajax.request({
			url:'/updateValue',
			params:{
				name:'AutoCancel',
				value:celTime
			},
			success:function(response){
				var jsonObj = response.responseText;
				var status=JSON.parse(jsonObj);
				if(("success")==(status.status)){
					Ext.MessageBox.alert("tip","Success");
				}else{
					Ext.MessageBox.alert("tip","Failure");
				}
			}
		});
	},
	autoAcp:function(){
		var acpTime=Ext.getCmp('acpTime').getValue();
		Ext.Ajax.request({
			url:'/updateValue',
			params:{
				name:'AutoAccept',
				value:acpTime
			},
			success:function(response){
				var jsonObj = response.responseText;
				var status=JSON.parse(jsonObj);
				if(("success")==(status.status)){
					Ext.MessageBox.alert("tip","Success");
				}else{
					Ext.MessageBox.alert("tip","Failure");
				}
			}
		});
	},
	updateTel:function(){
		var newTel=Ext.getCmp('newTel').getValue();
		Ext.Ajax.request({
			url:'/updateValue',
			params:{
				name:'HotLine',
				value:newTel
			},
			success:function(response){
				var jsonObj = response.responseText;
				var status=JSON.parse(jsonObj);
				if(("success")==(status.status)){
					Ext.MessageBox.alert("tip","Success");
				}else{
					Ext.MessageBox.alert("tip","Failure");
				}
			}
		});		
	}
});
