/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.homeController', {
    extend: 'Ext.app.Controller',
	
    init: function(application) {
        this.control({
           '#returnHome':{
			   click:this.returnHome
		   },
			'#customer':{
				click:this.customer
			},
			'#register':{
				click:this.register
			},
			'#store':{
				click:this.store
			},
			'#system':{
				click:this.system
            },
			'#MainView':{
				afterrender:this.beforeLoad
			}
        });	
    },
	returnHome:function(){
		window.location.href='/home/index.html';
	},
	customer:function(){
		window.location.href='/customer/customer.html';
		},
	register:function(){
		window.location.href='/business/business.html';
	},
	store:function(){
		window.location.href='/store/store.html';
	},
	system:function(){
		window.location.href='/setting/setting.html';
	},
	beforeLoad:function(){
			Ext.Ajax.request({
			url:'/approvingBusiness',
			
			success:function(response){
				var jsonObj = response.responseText;
				var status=Ext.decode(jsonObj);
				if(status.data){
					Ext.getCmp('unreadMessage').setText(status.data);
				}
			}
		});
	}
});
